name: Package

on:
  push:
    branches: [ "develop"]
    paths-ignore:
     - target/**
     - dist/**
  pull_request:
     branches: [ "develop" ]
     paths-ignore:
     - target/**
     - dist/**

env:
  ENV_VAR: test

jobs:
  Package-test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code 
      uses: actions/checkout@v2
      
    - name: Setup JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn clean install -DENV_VAR=${{ env.ENV_VAR }}
      
    - name: Build WAR file
      run: mvn -B package --file pom.xml
      
    - name: Upload WAR file as artifact
      uses: actions/upload-artifact@v2 
      with:
        name: HWC-API
        path: target/hwc-facility-service.war
